version: '3'
services:
  frontend:
    build: .
    build:
        context: ./frontend
    ports:
      - "8000:8000"
    environment:
      - ENDPOINT
  backend:
    build: .
    build:
        context: ./backend
    ports:
      - "9000:9000"
    environment:
      - APPID
